esphome:
  name: ald092cha-light
  name_add_mac_suffix: true

esp8266:
  board: esp01_1m

logger:

api:

ota:

dashboard_import:
  package_import_url: github://hpineapples/esphome-oem-test/ald092cha-light.yaml@main

wifi:
  ap:
    password: "7kmocjVrD6ad"

captive_portal:

sensor:
  - platform: wifi_signal
    name: "wifi_strength"
    update_interval: 60s
  - platform: uptime
    name: "uptime"
    update_interval: 60s

output:
  - platform: esp8266_pwm
    id: output_cw
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_ww
    pin: GPIO5

light:
  - platform: cwww
    name: ald092cha-light
    cold_white: output_cw
    warm_white: output_ww
    cold_white_color_temperature: 5700 K
    warm_white_color_temperature: 3000 K
    constant_brightness: true