# Arlec Grid Connect Smart 9W RGB CCT LED Downlight 
esphome:
  name: arlec-ald092rha-light
  name_add_mac_suffix: true

esp8266:
  board: esp01_1m

logger:

api:

ota:

wifi:
  ap:
    password: "123456788"

captive_portal:

sensor:
  - platform: wifi_signal
    name: "wifi_strength"
    update_interval: 60s
  - platform: uptime
    name: "uptime"
    update_interval: 60s

button:
  - platform: restart
    name: "restart"

# Put actual Config Here

output:
  - platform: esp8266_pwm
    id: output_cw
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_ww
    pin: GPIO5
  - platform: esp8266_pwm
    pin: GPIO12
    id: output_r
  - platform: esp8266_pwm
    pin: GPIO13
    id: output_b
  - platform: esp8266_pwm
    pin: GPIO14
    id: output_g

light:
  - platform: rgbww
    color_interlock: true
    name: arlec-ald092rha-light
    red: output_r
    green: output_g
    blue: output_b
    warm_white: output_ww
    cold_white: output_cw
    cold_white_color_temperature: 5700 K
    warm_white_color_temperature: 3000 K